databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    region: singapore
    plan: free

services:
  - type: web
    name: WebDemo
    runtime: python
    region: singapore
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn WebDemo.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
