# Generated by Django 3.2.23 on 2024-02-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('role', models.IntegerField(choices=[(1, 'admin'), (2, 'stuff')], verbose_name='role')),
                ('created_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习用户表',
                'verbose_name_plural': '学习用户表',
                'db_table': 'users',
            },
        ),
    ]
