# Generated by Django 3.2.23 on 2024-02-10 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_user_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'stuff')], verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='work',
            name='checkin_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 6, 14, 10, 660752, tzinfo=utc), verbose_name='check in time'),
        ),
        migrations.AlterField(
            model_name='work',
            name='checkout_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 6, 14, 10, 660752, tzinfo=utc), verbose_name='check out time'),
        ),
    ]
