# Generated by Django 3.2.23 on 2024-02-10 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_auto_20240210_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='checkin_time',
            field=models.DateTimeField(verbose_name='check in time'),
        ),
        migrations.AlterField(
            model_name='work',
            name='checkout_time',
            field=models.DateTimeField(verbose_name='check out time'),
        ),
    ]
