# Generated by Django 3.2.23 on 2024-02-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0010_auto_20240210_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'stuff')], verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='work',
            name='checkout_time',
            field=models.DateTimeField(null=True, verbose_name='check out time'),
        ),
    ]
